[tool.poetry]
name = "datatools"
version = "0.1.0"
description = ""
authors = ["Fill Later"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tables = "^3.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
